feat: Mint NFTs
refinableco/refinable-sdk pull request #1
Opened 2021-08-18 16:07 UTC by maximgeerinck

# Description

Allow the user to mint NFTs:

- ERC721
- ERC1155

With examples on how to use

Next to this, the SDK has also been cleaned up and starts from the point that the NFT object is the main object on which it continues.

2021-08-19 07:07 UTC, Superjo149 requested changes
Looks good, just a couple of remarks.

2021-08-19 07:07 UTC, Superjo149 commented on src/nft/ERC1155NFT.ts
> +    await result.wait(1);
Wouldn't hardcode this. Should be defined in `Refinable` and allowed to be overridden for each call.

2021-08-19 07:07 UTC, Superjo149 commented on src/nft/ERC721NFT.ts
> +
Isn't this what `verifyItem` does?

2021-08-19 07:07 UTC, Superjo149 commented on src/nft/ERC1155NFT.ts
>    async putForSale(price: Price, supply = 1): Promise<string> {
Do we also not want to check if the SDK is initialized here?

2021-08-19 07:07 UTC, Superjo149 commented on src/nft/ERC1155NFT.ts
>    cancelSale(): Promise<TransactionResponse> {
And here

2021-08-19 07:07 UTC, Superjo149 commented on src/nft/ERC721NFT.ts
> +    await result.wait(1);
Same

2021-08-19 07:07 UTC, Superjo149 commented on src/nft/TokenManager.ts
> +export const getContracts = (
Wouldn't it be cleaner to have this also in the `Refinable` class?

2021-08-19 09:55 UTC, maximgeerinck commented on src/Refinable.ts
> +        nft = new ERC721NFT(this, item) as NftRegistry[K];
not for now, it's too confusing for the user

2021-08-19 09:55 UTC, maximgeerinck commented on src/nft/AbstractNFT.ts
> +    return this.mintContract?.setApprovalForAll(address, true);
it's because of the lazy initializer. Not sure of a good way sadly

2021-08-19 09:56 UTC, maximgeerinck commented on src/Refinable.ts
> +  async createNft<K extends keyof NftRegistry>(
there are no good ways to call this :) you're making an NFT object. Minting is the creation terminology of an NFT

2021-08-19 09:57 UTC, maximgeerinck commented on src/nft/ERC721NFT.ts
> +
`verifyItem` checks whether the item is set. it can not be too generic because the token id is optional for the minting step

2021-08-19 09:57 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
>    async putForSale(price: Price, supply = 1): Promise<string> {
it won't continue unless it's initialized :) that's what the `build` does in the `Refinable` class

2021-08-19 09:58 UTC, maximgeerinck commented on src/nft/TokenManager.ts
> +export const getContracts = (
We could, but i thought it made more sense to split it up. no hard opinions, can move it if you prefer

2021-08-19 10:00 UTC, maximgeerinck commented on src/Refinable.ts
>      this._waitConfirmations = waitConfirmations;
good idea, added

2021-08-19 10:02 UTC, maximgeerinck commented on src/Refinable.ts
>    static create(provider: any, address: string, apiToken: string) {
Removed this, we can get it from the provider

2021-08-19 10:03 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
>    async putForSale(price: Price, supply = 1): Promise<string> {
Not sure, feels like typescript should be able to see this...

2021-08-19 10:07 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
>    async putForSale(price: Price, supply = 1): Promise<string> {
Added a way, not the prettiest

2021-08-19 10:41 UTC, Superjo149 commented on src/nft/TokenManager.ts
> +export const getContracts = (
If its really only our contracts that it is fetching, for me it makes sense to move it there.

2021-08-19 10:51 UTC, Superjo149 requested changes

2021-08-19 10:51 UTC, Superjo149 commented on src/Refinable.ts
> +  waitConfirmations: number;
If its user-facing, this should be optional with a default set by us.

2021-08-19 10:51 UTC, Superjo149 commented on src/Refinable.ts
> +  static create(provider: any, apiToken: string) {
Shouldn't you also (optionally) be able to pass the RefinableOptions here?

2021-08-19 10:51 UTC, Superjo149 commented on src/nft/AbstractNFT.ts
> +  protected saleContract: Contract = {} as any;
Is the tsconfig set more strict there? Because in our "sdk" we don't need initializers, and then we don't need funky stuff like this.

2021-08-19 10:51 UTC, Superjo149 commented on src/nft/ERC1155NFT.ts
> +        await this.refinable.provider.getAddress()
Can we also initialize this earlier, so that we don't have to fetch this each time?

2021-08-19 11:02 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
> +        await this.refinable.provider.getAddress()
yes

2021-08-20 07:08 UTC, Superjo149 reviewed
This is still some comments left open :)

2021-08-20 10:36 UTC, maximgeerinck commented on src/nft/AbstractNFT.ts
> +  file: any;
only stream is accepted

2021-08-20 10:36 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
> +      throw new Error("Couldn't upload image for NFT");
shouldn't be necessary as the library behind `uploadFile` should throw them

2021-08-20 10:37 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
> +    if (!createItem) {
`graphql-request` throws the errors

2021-08-20 10:39 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
> +    await result.wait(1);
Adjusted, was a leftover

2021-08-20 10:39 UTC, maximgeerinck commented
> This is still some comments left open :)

Thanks, didn't see those :D

2021-08-20 11:29 UTC, Superjo149 approved these changes

2021-08-20 11:37 UTC, merged