[dev-2487] x2y2 list for sale
refinableco/refinable-sdk pull request #147
Opened 2022-10-03 08:38 UTC by viet10101988

2022-10-03 10:43 UTC, sneljo1 requested changes

2022-10-03 10:43 UTC, sneljo1 commented on src/graphql/x2y2.ts
> +    query x2y2PostOrder($data: LocalOrder!) {
Should be a mutation

2022-10-03 10:43 UTC, sneljo1 commented on src/nft/ERC721NFT.ts
> +        if (platform === Platform.X2Y2) {
Can this not be simplified that we dont need the condition? Thats the whole reason for using the factory pattern. Some of the properties being passed are too specific to x2y2 and can be added inside of the `listForSale` implementation.

2022-10-03 16:41 UTC, mihaiberq reviewed
im impressed this works in so little lines of code :D

did you check by any chance if the reservoir listing is included?

2022-10-03 23:22 UTC, viet10101988 commented
> im impressed this works in so little lines of code :D
> 
> did you check by any chance if the reservoir listing is included?

some logic has to be moved to app because x2y2 doesn't allow requesting from browser

2022-10-04 00:13 UTC, viet10101988 commented on src/graphql/x2y2.ts
> +    query x2y2PostOrder($data: LocalOrder!) {
fixed

2022-10-04 00:13 UTC, viet10101988 commented on src/nft/ERC721NFT.ts
> +        if (platform === Platform.X2Y2) {
fixed

2022-10-04 06:46 UTC, sneljo1 requested changes
The parameter abstraction looks good, exactly what I was referring to, good job 👍  

The nested mutation with the resolveField is still a bit weird tho, dont think thats really allowed like that.

2022-10-04 06:46 UTC, sneljo1 commented on src/graphql/x2y2.ts
> +        x2y2Mutation {
Same remark here, nested mutations are not a thing. Needs to be flattened and something like postX2y2Order or a generic `postOrder` with variable `platform: X2y2`

2022-10-04 07:11 UTC, sneljo1 commented on src/graphql/x2y2.ts
> +        x2y2Mutation {
Or in line with the rest, z2y2ListForSale

2022-10-04 07:18 UTC, viet10101988 commented on src/graphql/x2y2.ts
> +        x2y2Mutation {
fixed

2022-10-04 07:25 UTC, sneljo1 approved these changes

2022-10-04 07:26 UTC, viet10101988 commented on src/graphql/x2y2.ts
> +        x2y2Mutation {
renamed

2022-10-04 07:26 UTC, merged