[DEV-2485] Opensea - list for sale
refinableco/refinable-sdk pull request #148
Opened 2022-10-03 11:11 UTC by mihaiberq

Currently in draft, wanna compare with X2Y2 pr first, to check for req changes

2022-10-04 03:18 UTC, viet10101988 commented on src/nft/ERC721NFT.ts
> +          const now = Math.floor(Date.now() / 1000);
this will also conflict with my PR since I refactored this part

2022-10-04 05:26 UTC, mihaiberq commented on src/nft/ERC721NFT.ts
> +          const now = Math.floor(Date.now() / 1000);
yes, yes, whoever gets approved last will have the joy of merging stuff :D :D :D

2022-10-04 07:00 UTC, sneljo1 requested changes

2022-10-04 07:00 UTC, sneljo1 commented on src/refinable/Refinable.ts
> +    const { chainId } = await this.evm.provider.getNetwork();
During init this will error because a user might not be authenticated yet

2022-10-07 07:16 UTC, sneljo1 commented on src/platform/OpenseaPlatform.ts
> +    throw new Error("Buy method not implemented yet");
Is it or is it not implemented?

2022-10-07 07:28 UTC, sneljo1 approved these changes

2022-10-07 08:38 UTC, mihaiberq commented on src/platform/OpenseaPlatform.ts
> +    throw new Error("Buy method not implemented yet");
initial copy-paste from putForSale, params still have to be changed to match the new ones. but the gist of it should be there

2022-10-07 08:39 UTC, merged