1427 custom token
refinableco/refinable-sdk pull request #153
Opened 2022-10-20 12:48 UTC by maximgeerinck

Allow using custom tokens in prices

2022-10-21 07:12 UTC, viet10101988 commented on src/nft/AbstractEvmNFT.ts
> +    console.log({ currency: price.currency, coin });
remove

2022-10-21 07:12 UTC, viet10101988 commented on src/offer/MintOffer.ts
> +        currency: this._offer.price.currency.id,
don't know why id field is introduced here

2022-10-21 07:12 UTC, viet10101988 commented on src/offer/MintOffer.ts
> +        currency: this._offer.price.currency.id,
same

2022-10-21 07:12 UTC, viet10101988 commented on src/offer/SaleOffer.ts
> +    if (resp.data.simulation.status === false) {
better use resp.data?.simulation?.status

2022-10-24 10:33 UTC, sneljo1 requested changes
Looks good, some of the comments regarding duplication we already discussed on Gather+ some other small ones

2022-10-24 10:33 UTC, sneljo1 commented on src/nft/AbstractEvmNFT.ts
> +      await this.getCurrency(priceWithServiceFee.currency),
Wouldn't it make sense for input to just be the currency contractAddress? This way we dont have to go resolve it each time. And we can just get the decimals from the chain allowing us to prevent making mistakes.

Especially since you are doing `getCoin` here and then also 2 lines later. If you already have the address, you only have to lookup the decimals. And since this is such a small value, we can easily just cache it in a map in the sdk.

2022-10-24 10:33 UTC, sneljo1 commented on src/nft/AbstractEvmNFT.ts
> +      await this.getCurrency(priceWithServiceFee.currency),
Same thing, Duplicate getCoin calls

2022-10-24 10:33 UTC, sneljo1 commented on src/offer/SaleOffer.ts
> +          this._offer.price.currency.ticker != "eth" ? "0" : unsignedTx.value,
For future, reference, it should use isnative instead

2022-10-24 10:33 UTC, sneljo1 commented on src/refinable/Chain.ts
> +  public getCoin({
Might be nice to keep a map to cache like we do for the contracts.

2022-10-24 11:20 UTC, maximgeerinck commented on src/offer/SaleOffer.ts
> +    if (resp.data.simulation.status === false) {
hmh, sure

2022-10-24 16:32 UTC, maximgeerinck commented on src/refinable/Chain.ts
> +  public getCoin({
reworked to not use coin id

2022-10-24 16:32 UTC, maximgeerinck commented on src/offer/SaleOffer.ts
> +          this._offer.price.currency.ticker != "eth" ? "0" : unsignedTx.value,
reworked to not use coin id

2022-10-24 16:32 UTC, maximgeerinck commented on src/nft/AbstractEvmNFT.ts
> +      await this.getCurrency(priceWithServiceFee.currency),
reworked to not use coin id

2022-10-24 16:32 UTC, maximgeerinck commented on src/nft/AbstractEvmNFT.ts
> +    console.log({ currency: price.currency, coin });
removed

2022-10-24 16:32 UTC, maximgeerinck commented on src/offer/SaleOffer.ts
> +          this._offer.price.currency.ticker != "eth" ? "0" : unsignedTx.value,
reworked to not use coin id

2022-10-24 16:32 UTC, maximgeerinck commented on src/nft/AbstractEvmNFT.ts
> +      await this.getCurrency(priceWithServiceFee.currency),
reworked to not use coin id

2022-10-25 08:09 UTC, mihaiberq commented
When fixing the conflict, it might help to mention that i move the `cancelSaleOffers` in `ERC721NFT` to `AbstractEvmNFT`, so it should be updated in there if there are conflicts

2022-10-25 08:13 UTC, mihaiberq commented on src/platform/OpenseaPlatform.ts
> +    const { orderParams: { parameters = {}, signature = "" } = {} } = offer;
this will break with the change of passing `offer.orderParams` rather than whole `offer` in `ERC721NFT` cancel sale method (check my other PR comment re moving the function)

2022-10-25 08:13 UTC, mihaiberq commented on src/nft/ERC721NFT.ts
> +        await externalPlatform.cancelSale(offer.orderParams, {
here i mean

2022-10-25 08:39 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +      price: {
Doesnt just `this._offer.price` suffice? Same for below

2022-10-25 08:39 UTC, sneljo1 commented on src/graphql/fragments.ts
> +        contract(chainId: $chainId) {
Still a bit weirded out by having to pass chainId, cant we just put a resolveField on price to populate the currency? This would make things much cleaner

2022-10-25 11:42 UTC, maximgeerinck commented on src/offer/MintOffer.ts
> +        currency: this._offer.price.currency.id,
removed

2022-10-25 11:42 UTC, maximgeerinck commented on src/offer/SaleOffer.ts
> +    if (resp.data.simulation.status === false) {
ok

2022-10-25 11:47 UTC, maximgeerinck commented on src/platform/OpenseaPlatform.ts
> +    const { orderParams: { parameters = {}, signature = "" } = {} } = offer;
will rework to only have to pass orderParams

2022-10-25 11:47 UTC, maximgeerinck commented on src/nft/ERC721NFT.ts
> +        await externalPlatform.cancelSale(offer.orderParams, {
will rework to only have to pass orderParams, so i can leave this

2022-10-25 11:49 UTC, maximgeerinck commented on src/nft/ERC721NFT.ts
> +        await externalPlatform.cancelSale(offer.orderParams, {
@mihaiberq do you remember where the `payToken` is in opensea order params?

2022-10-25 11:51 UTC, maximgeerinck commented on src/offer/MintOffer.ts
> +      price: {
yep, will change

2022-10-25 13:14 UTC, maximgeerinck commented on src/graphql/fragments.ts
> +        contract(chainId: $chainId) {
removed

2022-10-25 13:19 UTC, mihaiberq commented on src/nft/ERC721NFT.ts
> +        await externalPlatform.cancelSale(offer.orderParams, {
@maximgeerinck should be inside `orderParams.consideration[0].token` & the price `orderParams.consideration[0].startAmount`:
```
      paymentToken: parameters?.consideration[0]?.token,
      price: parameters?.consideration[0]?.startAmount,
```

2022-10-25 13:19 UTC, mihaiberq commented on src/nft/ERC721NFT.ts
> +        await externalPlatform.cancelSale(offer.orderParams, {
caveat is that `price` is actually `totalPrice - fee`

2022-10-25 13:34 UTC, sneljo1 approved these changes

2022-10-26 06:33 UTC, merged