[ENG-1157] [ENG-1115] List item on sale Solana
refinableco/refinable-sdk pull request #16
Opened 2021-10-27 02:33 UTC by viet10101988

- See README SOLANA

2021-11-02 04:34 UTC, viet10101988 commented
@Superjo149 you can review again

2021-11-02 08:22 UTC, Superjo149 requested changes
Looks much better, still don't really like having so much of the oyster stuff in our lib, but this can do for now. 

Just have a couple of small comments of the SOLNFT  code

2021-11-02 08:22 UTC, Superjo149 commented on src/nft/SOLNFT.ts
> +        endAuctionAt: isInstantSale
For simplicity, shall we just assume all the logic here is `isInstantSale` and remove the conditionals? If we need any other special features, we can add it later

2021-11-02 08:22 UTC, Superjo149 commented on src/nft/SOLNFT.ts
> +        tokenMint: QUOTE_MINT.toBase58(),
THis should be the publickKey of the token, in this case we'll probably put it in the tokenId field. So this should be `this.item.tokenId`.

2021-11-02 08:22 UTC, Superjo149 commented on src/nft/SOLNFT.ts
> +            length: new BN(attributes.editions || 1),
Can you add a TODO for supporting editions?

2021-11-02 08:22 UTC, Superjo149 commented on src/nft/SOLNFT.ts
> +        attributes.category === AuctionCategory.Open
Same here, there is too much conditional logic which we do not need for instant sale

2022-01-21 09:18 UTC, Superjo149 commented
Closing in favour of the upcoming PR

2022-01-21 09:18 UTC, closed without merging