[ENG-949] date for sale
refinableco/refinable-sdk pull request #23
Opened 2021-11-30 11:12 UTC by viet10101988

2021-12-06 10:07 UTC, Superjo149 requested changes
Small code style comment, no remarks otherwise. But its all still pending on the nft-contracts. changes. So I would hold off on merging

2021-12-06 10:07 UTC, Superjo149 commented on src/nft/ERC721NFT.ts
> +    saleEndDate?: Date
Its a bit weird having to send undefined for supply when wanting to use saleStartDate and/or enddate. Perhaps it would be better to have some kind of object for saleOptions

2022-01-13 10:26 UTC, maximgeerinck commented
is this PR still needed?

2022-01-13 10:28 UTC, Superjo149 commented
> is this PR still needed?

It is, yes. All the logic is good, but the functionality is pending the diamond contracts.

2022-03-15 14:55 UTC, closed without merging