Feat/support diamond
refinableco/refinable-sdk pull request #26
Opened 2021-12-28 10:29 UTC by deveshrawat

Description:

1. Update ERC721Sale and REC1155Sale methods
2. Update examples
3. Add functionality to check for tags to support auction and sale 
4. Update version

2021-12-29 11:15 UTC, maximgeerinck requested changes
as it stands right now i don't understand it :D 

We should only use the diamond contract for the chain we'll introduce next. the other chains should still use the sale contracts as defined before.

the diamond contract also acts as a big proxy towards the sales, so from my understanding, it should be sufficient to put this is a the value of `saleContract` ? not sure if i'm missing something.

2021-12-29 11:15 UTC, maximgeerinck commented on examples/listForSale.ts
> -        chainId: Chain.BscTestnet,
example should stay testnet

2021-12-29 11:15 UTC, maximgeerinck commented on src/config/sdk.ts
> +    ContractTag.SaleV4_0_0,
we have to find a way to only do  this for the imx chain

2021-12-29 11:15 UTC, maximgeerinck commented on src/nft/AbstractNFT.ts
> +    const diamondSale = await this.refinable.contracts.getRefinableContract(
this won't always be a diamondSale, we will do this in phases.

2021-12-29 11:22 UTC, deveshrawat commented on examples/listForSale.ts
> -        chainId: Chain.BscTestnet,
will update this.

2021-12-29 11:27 UTC, deveshrawat commented
Putting value in saleContract's place is not enough as proxies also needs taken care, as we don't have proxies for diamond contracts.

2021-12-29 11:30 UTC, maximgeerinck commented
> Putting value in saleContract's place is not enough as proxies also needs taken care, as we don't have proxies for diamond contracts.

still we should have backsupport for chains without diamond :)

2021-12-29 11:36 UTC, deveshrawat commented on src/config/sdk.ts
> +    ContractTag.SaleV4_0_0,
That was not the idea initially, we weren't just wanted to use diamond Contract for our existing solution? Need to think about it if we want to use this for specific chain >>>

2021-12-30 15:40 UTC, deveshrawat commented on src/nft/AbstractNFT.ts
> +    const diamondSale = await this.refinable.contracts.getRefinableContract(
Yes indeed this name is misleading changed the variable name

2021-12-30 15:41 UTC, deveshrawat commented on src/config/sdk.ts
> +    ContractTag.SaleV4_0_0,
Added a check for  a particular chain

2021-12-31 08:08 UTC, maximgeerinck approved these changes
The tests look more like integration tests and will require you to have a local chain running.
Honestly, this is hard to automate as local chains on CI/CD is a bit tricky for now.

2021-12-31 08:08 UTC, maximgeerinck commented on src/config/sdk.ts
> +        ContractTag.AirdropV1_0_0,
isn't auction also v4?

2021-12-31 08:08 UTC, maximgeerinck commented on tests/unit-tests/erc1155.test.ts
> +  const wallet = initializeWallet(PRIVATE_KEY, Chain.Local);
Better to work with a mock of wallet

2021-12-31 08:08 UTC, maximgeerinck commented on tests/unit-tests/erc1155.test.ts
> +    });
you need your local chain to work now?

2021-12-31 08:15 UTC, deveshrawat commented on src/config/sdk.ts
> +        ContractTag.AirdropV1_0_0,
We are testing it for Sale contracts for now but if everything goes well we will update the auction contracts as well, this is the beauty of diamond standard we can add a single contract while keeping everything as before, so currently we are deploying only sale contracts.

2021-12-31 08:16 UTC, deveshrawat commented on tests/unit-tests/erc1155.test.ts
> +  const wallet = initializeWallet(PRIVATE_KEY, Chain.Local);
Yeah, that sounds a better Idea will update this

2022-01-03 06:44 UTC, merged