[ENG-859] Auction
refinableco/refinable-sdk pull request #3
Opened 2021-09-21 13:35 UTC by maximgeerinck

# Description

Add Auction capabilities:

- Creating an auction (1155 and 721)
- Ending existing auctions
- Cancelling auctions

2021-09-22 06:52 UTC, mihaiberq approved these changes
one small question, but otherwise this looks good

2021-09-22 06:52 UTC, mihaiberq commented on public/listForAuction.csv
> +ContractAddress,TokenId,Type,Currency,Price,Supply
what is this used for? can't seem to find its reference in the code. if it's still used, should we store it as json maybe so we dont parse it every time?

2021-09-22 10:40 UTC, Superjo149 requested changes
Couple of remarks

2021-09-22 10:40 UTC, Superjo149 commented on README.md
> +2. `NODE_ENV npx esno src/examples/mint/mint721.ts`
Whats the difference?

2021-09-22 10:40 UTC, Superjo149 commented on README.md
> +```
This might be a bit confusing. I think it would also be best if we explained the differences

2021-09-22 10:40 UTC, Superjo149 commented on src/contracts.ts
> +export function getERC20Address(chainId: number, currency: PriceCurrency) {
A lot of this functionality in this file is actually more up-to-date in `@refinableco/lib`. So in the future, ideally we would also publish or share this package in some way I think.

2021-09-22 10:40 UTC, Superjo149 commented on src/nft/AbstractNFT.ts
> +    if (price.currency !== PriceCurrency.Bnb) {
This is no longer correct as this logic does not work multi-chain. In our code-base we use `isNativeCurrency` for this.

2021-09-22 10:40 UTC, Superjo149 commented on src/nft/AbstractNFT.ts
> +      // ethers.constants.AddressZero, // _royaltyToken
Yeah, this is a new addition. We'll soon run into versioning issues I think.

2021-09-22 13:44 UTC, maximgeerinck commented on README.md
> +2. `NODE_ENV npx esno src/examples/mint/mint721.ts`
it is normally up to 5 times faster, but it doesn't always work, so i'll revert it :)

2021-09-22 13:48 UTC, maximgeerinck commented on README.md
> +```
you're right, adjusting

2021-09-22 13:48 UTC, maximgeerinck commented on src/contracts.ts
> +export function getERC20Address(chainId: number, currency: PriceCurrency) {
That's an internal package right now :) Let's see how we can merge this when we integrate it in our codebase

2021-09-22 14:12 UTC, maximgeerinck commented on src/nft/AbstractNFT.ts
> +    if (price.currency !== PriceCurrency.Bnb) {
Will rework for multi chain according to new changes

2021-09-24 07:23 UTC, maximgeerinck commented on public/listForAuction.csv
> +ContractAddress,TokenId,Type,Currency,Price,Supply
Was old, not used anymore. deleted it :)

2021-09-27 09:14 UTC, deveshrawat approved these changes
Looks ok to me!

2021-09-27 10:33 UTC, Superjo149 approved these changes

2021-09-27 11:41 UTC, merged