[DEV-1553] [DEV-1501] [DEV-1566] Deploy auction contracts for diamond
refinableco/refinable-sdk pull request #31
Opened 2022-01-19 06:24 UTC by viet10101988

- Contract v4 for Polygon and BSC

2022-01-19 09:43 UTC, Superjo149 requested changes

2022-01-19 09:43 UTC, Superjo149 commented on src/config/sdk.ts
> +        chain === ChainType.POLYGON
Its already deployed for BSC, so why not leave it also? We'll need to align everything in the end either way.

2022-01-19 09:43 UTC, Superjo149 commented on src/nft/AbstractNFT.ts
> +    }
The line above `await this.approveIfNeeded(this.auctionContract.address);` should be included in the else statement here. No need to approve the auction contracts anymore in this case.

Or to make it cleaner
```ts
const addressToApprove = isDiamondContract ? this.transferProxyContract.address : this.auctionContract.address;
await this.approveIfNeeded(addressToApprove);
```

2022-01-19 09:43 UTC, Superjo149 commented on src/nft/AbstractNFT.ts
> +    } catch (err) {
Please remove the try catch

2022-01-20 06:13 UTC, deveshrawat commented on src/config/sdk.ts
> +        chain === ChainType.POLYGON
Only sale contracts are deployed, so can keep that, but I would prefer testing it on polygon first with sale/auction then deploying contracts on BSC ?

2022-01-20 07:18 UTC, Superjo149 commented on src/config/sdk.ts
> +        chain === ChainType.POLYGON
Its easier the sooner we do it, because if we do it before we go to testnet. You can just include it in the other migration

2022-01-20 07:20 UTC, Superjo149 approved these changes

2022-01-20 07:41 UTC, merged