WIP
refinableco/refinable-sdk pull request #32
Opened 2022-01-21 10:37 UTC by Superjo149

2022-01-25 03:53 UTC, viet10101988 requested changes

2022-01-25 03:53 UTC, viet10101988 commented on src/offer/SaleOffer.ts
>      await this.refinable.apiClient.request<
can the this.nft.buy() before fail? If so need to adjust this call accordingly

2022-01-25 03:53 UTC, viet10101988 commented on src/refinable/account/SolanaAccount.ts
> +    const result = await this.refinable.connection.getBalance(
could this fail? Might break other places if they use getBalance()

2022-01-25 03:53 UTC, viet10101988 commented on src/transaction/EvmTransaction.ts
> +    if (!this.txReceipt) throw new Error("Must await tx first");
do we need throw if this is just a get()?

2022-01-25 03:53 UTC, viet10101988 commented on src/transaction/SolanaTransaction.ts
> +    if (!this.txResult) throw new Error("Must await tx first");
same as above

2022-01-25 07:49 UTC, maximgeerinck approved these changes
Looking rather good for such a PR, small things but nothing too serious i think.
Just find the 2 refinable clients confusing and not that user friendly.

2022-01-25 07:49 UTC, maximgeerinck commented on examples/item/itemsOnAuction.ts
> +    const refinable = await RefinableEvmClient.create(wallet, API_KEY, {
not sure why we didn't put this in a factory with a network selector

2022-01-25 07:49 UTC, maximgeerinck commented on src/config/sdk.ts
> -          : ContractTag.AuctionV3_1_0,
why was the v4 removed? it's the diamond contract

2022-01-25 07:49 UTC, maximgeerinck commented on src/solana/actions/addTokensToVault.ts
> +  )[0];
potential error ([0])

2022-01-25 07:49 UTC, maximgeerinck commented on src/solana/constants/labels.ts
> +};
do we need these?

2022-01-25 07:49 UTC, maximgeerinck commented on src/utils/connection.ts
> +  return new Connection(chain.nodeUri[0]);
chain can be not found

2022-01-25 07:52 UTC, Superjo149 commented on src/solana/actions/addTokensToVault.ts
> +  )[0];
This is how its done, if its a potential error, its an errr in 500 places :D

2022-01-25 07:53 UTC, Superjo149 commented on src/config/sdk.ts
> -          : ContractTag.AuctionV3_1_0,
Woops, testing purposes on local

2022-01-25 07:53 UTC, Superjo149 commented on examples/item/itemsOnAuction.ts
> +    const refinable = await RefinableEvmClient.create(wallet, API_KEY, {
This is the case, just not using it in this example. Will adjust

2022-01-28 08:41 UTC, deveshrawat approved these changes
Seems ok

2022-01-28 08:41 UTC, deveshrawat commented on src/solana/oyster/models/metaplex/startAuction.ts
> +  });
leftover ??

2022-01-28 11:43 UTC, Superjo149 commented on src/nft/solana/connection.ts
> +  for (let i = 0; i < signedTxns.length; i++) {
Because they are not supposed to be running parallel

2022-01-28 11:46 UTC, Superjo149 commented on src/offer/SaleOffer.ts
>      await this.refinable.apiClient.request<
If it fails, it will throw an error

2022-01-28 11:48 UTC, Superjo149 commented on src/refinable/account/SolanaAccount.ts
> +    const result = await this.refinable.connection.getBalance(
Not sure what you mean

2022-01-28 11:48 UTC, Superjo149 commented on src/transaction/EvmTransaction.ts
> +    if (!this.txReceipt) throw new Error("Must await tx first");
Yes, that the whole idea behind the wait

2022-01-28 11:49 UTC, Superjo149 commented on src/utils/connection.ts
> +  return new Connection(chain.nodeUri[0]);
The utility method already handles this

2022-01-28 11:49 UTC, Superjo149 commented on src/solana/oyster/models/metaplex/startAuction.ts
> +  });
Yeah, still quite some logs everywhere

2022-01-31 07:25 UTC, merged