[DEV-1215] Support refreshing metadata on NFTs
refinableco/refinable-sdk pull request #33
Opened 2022-01-28 12:18 UTC by mihaiberq

Add refresh metadata to SDK and use it from here

2022-01-28 13:13 UTC, Superjo149 requested changes

2022-01-28 13:13 UTC, Superjo149 commented on src/nft/AbstractNFT.ts
> +            type: this.type,
Same as I said on the other PR, this prop is not needed

2022-01-31 11:32 UTC, mihaiberq commented
i re-requested your reviewed based on the fact that type is needed (https://github.com/refinableco/refinable/pull/1240#discussion_r795491541)

2022-01-31 15:56 UTC, Superjo149 approved these changes

2022-01-31 16:58 UTC, merged