Support launchpads
refinableco/refinable-sdk pull request #37
Opened 2022-02-03 09:07 UTC by maximgeerinck

Support VIP, Private, Public sales

2022-02-03 10:15 UTC, Superjo149 requested changes

2022-02-03 10:15 UTC, Superjo149 commented on src/nft/ERC1155NFT.ts
> +        getUnixEpochTimeStampFromDate(launchpadDetails.vipStartDate),
Can any of these be undefined? Also, do we want to await for confirmation before proceeding to save?

2022-02-03 10:21 UTC, maximgeerinck commented on src/nft/ERC1155NFT.ts
> +        getUnixEpochTimeStampFromDate(launchpadDetails.vipStartDate),
no they can not be undefined, it's defined like that in the types. Waiting is a good idea, added it

2022-02-04 10:13 UTC, Superjo149 approved these changes

2022-02-08 12:21 UTC, merged