[DEV-1481] Create collection
refinableco/refinable-sdk pull request #54
Opened 2022-03-24 09:13 UTC by mihaiberq

Base code to allow for `RefinableWhitelistedToken` contract creation in the sdk

2022-03-24 09:22 UTC, sneljo1 reviewed
I think we should either create the contract via our API after deployment, or create a separate method to do so. Because right now this is a bit useless. If the user uses the SDK standalone. yes he created his contract, but can't even use it with us.

2022-03-24 09:22 UTC, sneljo1 commented on src/refinable/Contracts.ts
> +    return new EvmTransaction(contract.deployTransaction);
Are we able to retrieve the contract address from this? Otherwise would make sure that we do

2022-03-24 09:25 UTC, mihaiberq commented on src/refinable/Contracts.ts
> +    return new EvmTransaction(contract.deployTransaction);
yes, im also displaying contract address + tx hash in the modal + success page.

2022-03-24 09:27 UTC, mihaiberq commented
hmmm ok, ill add a separate function to create the contract

2022-03-24 09:36 UTC, sneljo1 commented
> hmmm ok, ill add a separate function to create the contract

If we do that, we'll need to make it clear tho to the user that this is required

2022-03-24 15:28 UTC, sneljo1 requested changes

2022-03-24 15:28 UTC, sneljo1 commented on src/refinable/Contracts.ts
> +            contractType: type,
I would send the abi, less work for the backend.

2022-03-24 15:28 UTC, sneljo1 commented on src/refinable/Contracts.ts
> +    collection: SdkCollectionInput
All of these different params are a bit messy. Would make more sense if the contract properties are a property of the collection input as collection is the parent?

2022-03-25 06:40 UTC, mihaiberq commented on src/refinable/Contracts.ts
> +            contractType: type,
i would still have to verify the abi in the backend (not to allow random, broken abis to be sent to that endpoint), so id rather keep it like this

2022-03-25 07:25 UTC, sneljo1 approved these changes
LGTM

2022-03-25 08:11 UTC, merged