feat(DEV-1426): add store fees
refinableco/refinable-sdk pull request #62
Opened 2022-04-14 10:58 UTC by sneljo1

- Parameter restructuring for contract changes
- Remove royaltyToken
- Add support for MarketConfig
- Abstract away buyerFee login inside of the offer fetchingd

2022-04-14 15:10 UTC, maximgeerinck commented on src/config/sdk.ts
> +          : ContractTag.AuctionV3_2_0,
same here

2022-04-14 15:12 UTC, maximgeerinck commented on src/refinable/RefinableBaseClient.ts
> +    if (!queryResponse?.offer) return null;
would throw an error

2022-04-14 15:12 UTC, maximgeerinck commented on src/refinable/RefinableBaseClient.ts
> +    return OfferFactory.createOffer(this, queryResponse?.offer, nft) as any;
`any` ?

2022-04-14 15:14 UTC, maximgeerinck commented on src/store/Store.ts
> +    return this.refinable.getOffer(offerId, this.id);
i would have done a new query here, doesn't make sense to put `storeId` under `offer` when the offer belongs to the store

2022-04-14 15:14 UTC, maximgeerinck commented on src/store/Store.ts
> +    return this.refinable.getOffer(offerId, this.id);
or make `this.id` part of an `option` list

2022-04-15 07:00 UTC, sneljo1 commented on src/store/Store.ts
> +    return this.refinable.getOffer(offerId, this.id);
`option` list? Instead of having the second param be the storeId, be an object? I did it just to be flexible. The way you can also do `getOffer` and requesting the store info from there.

2022-04-15 07:01 UTC, sneljo1 commented on src/refinable/RefinableBaseClient.ts
> +    if (!queryResponse?.offer) return null;
Hmm, but if the offer is no longer active it would also throw an error. Would't that cause too many cases of handling it?

2022-04-15 07:20 UTC, mihaiberq requested changes
i agree with maxim, maybe we should tag the contracts as v4? other than that, looks gucci

2022-04-15 11:38 UTC, mihaiberq approved these changes

2022-04-15 12:37 UTC, sneljo1 commented
Merging pending @maximgeerinck re-review as discussed through DM

2022-04-15 12:38 UTC, merged