[ENG-1911] Create MintOffers
refinableco/refinable-sdk pull request #69
Opened 2022-05-04 13:42 UTC by maximgeerinck

# Description

- Allow creating mint offers 
- Created offers namespace
- Refactored chain

2022-05-04 14:09 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +      nonce: 0,
Nonce 0? :D

2022-05-04 14:10 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +    return response?.createMintOffer;
Should we return the offer class itself like with Sale?

2022-05-04 14:13 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +        endTime: message?.endTime ?? Math.floor((Date.now() + 31622400) / 1000), // 1 year late
Would avoid passing default because there will be a conflicts between the signature data and the data saved to the backend. If we want default, they need to be applied also to the data going to the backend. For dates I think we can fallback to 0 anyway?

2022-05-04 14:14 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +  private async getSupplyOnSale() {
Might not be needed here

2022-05-04 15:59 UTC, maximgeerinck commented on src/offer/MintOffer.ts
> +      nonce: 0,
Forgot to fix this. added :)

2022-05-04 16:00 UTC, maximgeerinck commented on src/offer/MintOffer.ts
> +  private async getSupplyOnSale() {
removed

2022-05-04 16:00 UTC, maximgeerinck commented
> Also, some e2e tests, could also be in the next PR, would be nice to be able to quickly test the whole flow

ye, agreed. Will add some next PR

2022-05-05 06:11 UTC, sneljo1 requested changes
Still couple of small remarks

2022-05-05 06:11 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +      nonce: 0,
Nonce is still not set :D

2022-05-05 06:11 UTC, sneljo1 commented on src/offer/MintOffer.ts
> +        name: "Refinable Mint",
Can you also create a PR for `nft-contracts`?

2022-05-05 07:34 UTC, maximgeerinck commented on src/offer/MintOffer.ts
> +      nonce: 0,
added

2022-05-05 07:34 UTC, maximgeerinck commented on src/offer/MintOffer.ts
> +        name: "Refinable Mint",
made

2022-05-05 07:35 UTC, sneljo1 approved these changes

2022-05-05 08:06 UTC, merged